// Generated by gencpp from file ssafy_2/GpsService.msg
// DO NOT EDIT!


#ifndef SSAFY_2_MESSAGE_GPSSERVICE_H
#define SSAFY_2_MESSAGE_GPSSERVICE_H

#include <ros/service_traits.h>


#include <ssafy_2/GpsServiceRequest.h>
#include <ssafy_2/GpsServiceResponse.h>


namespace ssafy_2
{

struct GpsService
{

typedef GpsServiceRequest Request;
typedef GpsServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsService
} // namespace ssafy_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ssafy_2::GpsService > {
  static const char* value()
  {
    return "a521110ed02262d566473f15c18bcdf5";
  }

  static const char* value(const ::ssafy_2::GpsService&) { return value(); }
};

template<>
struct DataType< ::ssafy_2::GpsService > {
  static const char* value()
  {
    return "ssafy_2/GpsService";
  }

  static const char* value(const ::ssafy_2::GpsService&) { return value(); }
};


// service_traits::MD5Sum< ::ssafy_2::GpsServiceRequest> should match
// service_traits::MD5Sum< ::ssafy_2::GpsService >
template<>
struct MD5Sum< ::ssafy_2::GpsServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ssafy_2::GpsService >::value();
  }
  static const char* value(const ::ssafy_2::GpsServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssafy_2::GpsServiceRequest> should match
// service_traits::DataType< ::ssafy_2::GpsService >
template<>
struct DataType< ::ssafy_2::GpsServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ssafy_2::GpsService >::value();
  }
  static const char* value(const ::ssafy_2::GpsServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ssafy_2::GpsServiceResponse> should match
// service_traits::MD5Sum< ::ssafy_2::GpsService >
template<>
struct MD5Sum< ::ssafy_2::GpsServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ssafy_2::GpsService >::value();
  }
  static const char* value(const ::ssafy_2::GpsServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssafy_2::GpsServiceResponse> should match
// service_traits::DataType< ::ssafy_2::GpsService >
template<>
struct DataType< ::ssafy_2::GpsServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ssafy_2::GpsService >::value();
  }
  static const char* value(const ::ssafy_2::GpsServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SSAFY_2_MESSAGE_GPSSERVICE_H
