// Generated by gencpp from file ssafy_2/GpsServiceResponse.msg
// DO NOT EDIT!


#ifndef SSAFY_2_MESSAGE_GPSSERVICERESPONSE_H
#define SSAFY_2_MESSAGE_GPSSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssafy_2
{
template <class ContainerAllocator>
struct GpsServiceResponse_
{
  typedef GpsServiceResponse_<ContainerAllocator> Type;

  GpsServiceResponse_()
    : result(false)  {
    }
  GpsServiceResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GpsServiceResponse_

typedef ::ssafy_2::GpsServiceResponse_<std::allocator<void> > GpsServiceResponse;

typedef boost::shared_ptr< ::ssafy_2::GpsServiceResponse > GpsServiceResponsePtr;
typedef boost::shared_ptr< ::ssafy_2::GpsServiceResponse const> GpsServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssafy_2::GpsServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssafy_2::GpsServiceResponse_<ContainerAllocator1> & lhs, const ::ssafy_2::GpsServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssafy_2::GpsServiceResponse_<ContainerAllocator1> & lhs, const ::ssafy_2::GpsServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssafy_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::ssafy_2::GpsServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssafy_2/GpsServiceResponse";
  }

  static const char* value(const ::ssafy_2::GpsServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::ssafy_2::GpsServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssafy_2::GpsServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssafy_2::GpsServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSAFY_2_MESSAGE_GPSSERVICERESPONSE_H
