(cl:defpackage ssafy_2-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "GPSSERVICE"
   "<GPSSERVICE-REQUEST>"
   "GPSSERVICE-REQUEST"
   "<GPSSERVICE-RESPONSE>"
   "GPSSERVICE-RESPONSE"
  ))

